/* Populated by react-webpack-redux:action */
export const SAY_HELLO = 'SAY_HELLO'
export const UPLOAD_PRODUCT_ZIP = 'UPLOAD_PRODUCT_ZIP'
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
export const DELETE_PRODUCT_BY_ID = 'DELETE_PRODUCT_BY_ID'
export const DELETE_PRODUCT_IMAGE_BY_NAME = 'DELETE_PRODUCT_IMAGE_BY_NAME'
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT'
export const DELETE_PRODUCT_DATA_BY_ID = 'DELETE_PRODUCT_DATA_BY_ID'
export const UPDATE_PRODUCT_DATA_BY_ID = 'UPDATE_PRODUCT_DATA_BY_ID'
export const ADD_PRODUCT_DATA_BY_ID = 'ADD_PRODUCT_DATA_BY_ID'
export const UPDATE_PRODUCT_DESC_BY_ID = 'UPDATE_PRODUCT_DESC_BY_ID'

