/* Populated by react-webpack-redux:action */
export const SAY_HELLO = 'SAY_HELLO'

// product
export const UPLOAD_PRODUCT_ZIP = 'UPLOAD_PRODUCT_ZIP'
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
export const DELETE_PRODUCT_BY_ID = 'DELETE_PRODUCT_BY_ID'
export const DELETE_PRODUCT_IMAGE_BY_IMAGE_ID = 'DELETE_PRODUCT_IMAGE_BY_IMAGE_ID'
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT'
export const DELETE_PRODUCT_DATA_BY_ID = 'DELETE_PRODUCT_DATA_BY_ID'
export const UPDATE_PRODUCT_DATA_BY_ID = 'UPDATE_PRODUCT_DATA_BY_ID'
export const ADD_PRODUCT_DATA_BY_ID = 'ADD_PRODUCT_DATA_BY_ID'
export const UPDATE_PRODUCT_DESC_BY_ID = 'UPDATE_PRODUCT_DESC_BY_ID'
export const UPDATE_PRODUCT_CATEGORY_BY_ID = 'UPDATE_PRODUCT_CATEGORY_BY_ID'


// user
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID'
export const UPDATE_USER_BY_ID = 'UPDATE_USER_BY_ID'
export const GET_USER_LIST = 'GET_USER_LIST'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'


// category
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_CATEGORY_SUB = 'ADD_CATEGORY_SUB'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_SUB = 'DELETE_CATEGORY_SUB'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const UPDATE_CATEGORY_SUB = 'UPDATE_CATEGORY_SUB'
export const UPDATE_CATEGORY_SUB_IMAGE = 'UPDATE_CATEGORY_SUB_IMAGE'
